### ISSUE TITLE
Enabling profiler for aspnetcore/netframework Azure Web App causes HTTP 502.5 error

### ISSUE THREAD

**Issue by MikeLarah** [Microsoft/ApplicationInsights-aspnetcore#580]
## Repro Steps
1. Create new AspNetCore web application with .NET Framework
2. Install Microsoft.ApplicationInsights.AspNetCore package via NuGet
3. Publish to Azure Web App
4. Add APPINSIGHTS_INSTRUMENTATIONKEY app setting to Web App
5. Add Application Insights Azure Extension via Kudu

##  Actual Behavior

Requests to site result in HTTP Error 502.5 - Process Failure 

Looking at the event log reveals:
```
    <Event>
        <System>
            <Provider Name=".NET Runtime"/>
            <EventID>1026</EventID>
            <Level>1</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2017-12-19T16:02:11Z"/>
            <EventRecordID>3052968</EventRecordID>
            <Channel>Application</Channel>
            <Computer>RD00155D89889B</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Application: WebApplication1.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeLoadException
   at &lt;Module&gt;.__EnsureBootstrap__System.Diagnostics.DiagnosticSource.dll()
   at System.Diagnostics.DiagnosticListener..cctor()

Exception Info: System.TypeInitializationException
   at System.Diagnostics.DiagnosticListener..ctor(System.String)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(System.AggregateException ByRef)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at WebApplication1.Program.BuildWebHost(System.String[])
   at WebApplication1.Program.Main(System.String[])

</Data>
        </EventData>
    </Event>
```

## Expected Behavior

Site continues to work as normal, profiler is enabled.

## Version Info 
SDK Version : 2.1.1
.NET Version :	.NET Framework 4.6.1 / 4.7					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : NuGet & Azure Extension
OS : Windows
Hosting Info (IIS/Azure WebApps/ etc) : Azure WebApps

**Comment by hbiarge** [comment]
Same problem here

**Comment by jcemoller** [comment]
+1. Enabling stdout logging reveals the following error for me:
```

Error:
  An assembly specified in the application dependencies manifest (Microsoft.AspNetCore.ApplicationInsights.HostingStartup.deps.json) was not found:
    package: 'Microsoft.CSharp', version: '4.3.0'
    path: 'lib/netstandard1.3/Microsoft.CSharp.dll'
```

(.NET Core 2.0.3 - using .All package)

**Comment by clguimanMSFT** [comment]
Please go to the Kudu console, click on 'Tools->Diagnostic dump' and send the logs to clguiman@microsoft.com

**Comment by clguimanMSFT** [comment]
The issue should be fixed in v 2.4.8 of Application Insights Extension. Please update to the latest version

**Comment by pellea** [comment]
It still not working after updating to the 2.4.8 version. Removing the App Insight extension solved the issue.

**Comment by clguimanMSFT** [comment]
@pellea please send the logs to clguiman@microsoft.com

**Comment by pellea** [comment]
Same log as @jcemoller 


> Error:
>   An assembly specified in the application dependencies manifest (Microsoft.AspNetCore.ApplicationInsights.HostingStartup.deps.json) was not found:
>     package: 'Microsoft.CSharp', version: '4.3.0'
>     path: 'lib/netstandard1.3/Microsoft.CSharp.dll'

**Comment by cijothomas** [comment]
@clguimanMSFT Can i close this issue, assuming extension update has fixed this issue.
